# Generated by Django 5.1.3 on 2024-12-04 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=10, verbose_name='User Type')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Phone Number')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Dob')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('designation', models.CharField(blank=True, max_length=256, null=True, verbose_name='Designation')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('otp', models.CharField(blank=True, max_length=4, null=True, verbose_name='OTP')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('email_verify', models.BooleanField(default=False, verbose_name='Email Verify')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('user_anouncement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_anouncement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('in_time', models.DateTimeField(auto_now_add=True, verbose_name='In Time')),
                ('out_time', models.DateTimeField(auto_now_add=True, verbose_name='Out Time')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration')),
                ('attendance_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_leave', models.FloatField(default=0, verbose_name='Earned Leave')),
                ('sick_leave', models.FloatField(default=0, verbose_name='Sick Leave')),
                ('leave_balance_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('leave_type', models.CharField(choices=[('Earned', 'Earned Leave'), ('Sick', 'Sick Leave'), ('Casual', 'Casual Leave')], max_length=20, verbose_name='Leave Type')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status')),
                ('approved_on', models.DateTimeField(blank=True, null=True, verbose_name='Approved On')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('leave_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
