# Generated by Django 5.1.3 on 2024-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='In Time'),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Out Time'),
        ),
    ]
