# Generated by Django 5.1.4 on 2024-12-10 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_attendancemodel_in_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='RegularizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('in_time', models.TimeField(blank=True, null=True, verbose_name='In Time')),
                ('out_time', models.TimeField(blank=True, null=True, verbose_name='Out Time')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reason')),
                ('approval', models.BooleanField(default=False, verbose_name='Approval')),
                ('user_regularization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regularization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
