# Generated by Django 5.1.4 on 2024-12-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_leavebalancemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='emp_code',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, verbose_name='Gender'),
        ),
    ]
