# Generated by Django 5.1.4 on 2024-12-18 11:25

import apis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_myuser_emp_code_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=10, verbose_name='User Type'),
        ),
        migrations.CreateModel(
            name='AttendanceInOutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('image', models.ImageField(upload_to=apis.models.user_directory_path)),
                ('image_type', models.CharField(choices=[('IN', 'In Time'), ('OUT', 'Out Time')], max_length=3)),
                ('image_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apis.attendancemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
