# Generated by Django 5.1.4 on 2025-01-09 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_leavesmodel_dayoption_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAR', 'Aadhar'), ('PAN', 'PAN'), ('MARKSHEET_10', '10th Marksheet'), ('MARKSHEET_12', '12th Marksheet'), ('GRADUATION', 'Graduation Certificate'), ('POST_GRADUATION', 'Post Graduation Certificate'), ('CHEQUE', 'Cancelled Cheque'), ('PASSBOOK', 'Passbook'), ('OFFER_LETTER', 'Offer Letter'), ('EXP_LETTER', 'Experience Letter'), ('PAYSLIP', 'Payslip')], max_length=20)),
                ('file', models.FileField(upload_to='user_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
