# Generated by Django 5.1.4 on 2025-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_leavesmodel_dayoption_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesmodel',
            name='dayoption',
            field=models.CharField(choices=[('half', 'half'), ('full', 'full')], default='full', max_length=20, verbose_name='Day Option'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=10, verbose_name='User Type'),
        ),
    ]
