# Generated by Django 5.1.4 on 2025-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_leavesmodel_dayoption_alter_myuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalancemodel',
            name='used_earned_leave',
            field=models.FloatField(default=0, verbose_name='Used Earned Leave'),
        ),
        migrations.AddField(
            model_name='leavebalancemodel',
            name='used_sick_leave',
            field=models.FloatField(default=0, verbose_name='Used Sick Leave'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=20, verbose_name='Gender'),
        ),
    ]
