# Generated by Django 5.1.4 on 2025-01-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_leavebalancemodel_used_earned_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='Admin', max_length=10, verbose_name='User Type'),
        ),
    ]
