# Generated by Django 5.1.4 on 2025-01-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], max_length=20, verbose_name='Gender'),
        ),
    ]
